import type { VerdictVariant } from '../content-types'

export const srVerdicts = [
  {
    id: "sr_time_5min_red",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["sr_five_minutes"],
    reviewLine: "Da li je igrač uopšte krenuo?",
    sanction: "Crveni karton",
    offense: "Večnih pet minuta",
    explanation: "Snimak potvrđuje da je u trenutku slanja poruke još birao šta će da obuče.",
    penalty: "Oduzima mu se pravo da kaže „krećem“ do kraja sezone.",
    caseCode: "5MIN",
  },
  {
    id: "sr_time_status_yellow",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: ["sr_on_my_way", "sr_repeated_delay"],
    fallback: true,
    reviewLine: "Da li je ovo vreme dolaska?",
    sanction: "Žuti karton",
    offense: "Večnih pet minuta",
    explanation: "Status je stigao. Vreme dolaska nije.",
    penalty: "Sledeći izveštaj mora da sadrži vreme.",
    caseCode: "ETA01",
  },
  {
    id: "sr_time_now_yellow",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: ["sr_leaving_now"],
    reviewLine: "Da li reč „sad“ ima važeći rok?",
    sanction: "Žuti karton",
    offense: "Krećem, ali još ne",
    explanation: "Poruka je poslata pre nego što su pronađeni ključevi, jakna i volja.",
    penalty: "Sledeće „krećem“ priznaje se tek nakon izlaska iz zgrade.",
    caseCode: "SAD01",
  },
  {
    id: "sr_time_almost_red",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["sr_almost_there"],
    reviewLine: "Koliko zagrevanje može da traje?",
    sanction: "Crveni karton",
    offense: "Beskonačno zagrevanje",
    explanation: "Igrač je završio tri faze spremanja i još nije napustio stan.",
    penalty: "Vreme dolaska računa se tek od prvog koraka van kuće.",
    caseCode: "SNISAM",
  },
  {
    id: "sr_dry_vazi_yellow",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["sr_vazi"],
    reviewLine: "Da li je ovo odgovor ili upozorenje?",
    sanction: "Žuti karton",
    offense: "Dry",
    explanation: "Stiglo je „važi.“ i sad proveravaš poslednjih šest poruka.",
    penalty: "Bez „je l’ sve okej?“ narednih deset minuta.",
    caseCode: "DRY01",
  },
  {
    id: "sr_dry_short_yellow",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["sr_short_reply", "sr_dry_contextual"],
    fallback: true,
    reviewLine: "Da li se igra nastavlja?",
    sanction: "Žuti karton",
    offense: "Dry",
    explanation: "Odgovor je stigao. Sad si ti na potezu. Koji tačno, niko ne zna.",
    penalty: "Ne diraj ništa.",
    caseCode: "DRY02",
  },
  {
    id: "sr_dry_k_yellow",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["sr_k_reply"],
    reviewLine: "Da li jedno slovo ispunjava minimum?",
    sanction: "Žuti karton",
    offense: "K.",
    explanation: "Stiglo je „K.“ i odjednom „okej“ deluje kao roman.",
    penalty: "Sledeća poruka mora da sadrži najmanje jednu celu reč.",
    caseCode: "KONLY",
  },
  {
    id: "sr_dry_reaction_red",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "red",
    triggerIds: ["sr_reaction_only"],
    reviewLine: "Da li reakcija završava razgovor?",
    sanction: "Crveni karton",
    offense: "👍 i gotovo",
    explanation: "Stigao je 👍. Tehnički je sve u redu. Verovatno.",
    penalty: "Reakcije su suspendovane dok se ne pojavi puna rečenica.",
    caseCode: "THUMB1",
  },
  {
    id: "sr_excuse_seen_red",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["sr_didnt_see"],
    reviewLine: "Izgovor ide na proveru.",
    sanction: "Crveni karton",
    offense: "Simuliranje",
    explanation: "Poruka navodno nije viđena. Odgovor je ipak stigao baš na nju.",
    penalty: "Tehnički izgovori suspendovani su naredna tri kola.",
    caseCode: "SEEN",
  },
  {
    id: "sr_excuse_just_saw_yellow",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "yellow",
    triggerIds: ["sr_just_saw"],
    reviewLine: "VAR vraća vreme viđenja.",
    sanction: "Žuti karton",
    offense: "Baš sad?",
    explanation: "„Tek sad vidim.“ Baš sad. Kakva slučajnost.",
    penalty: "Sledeće „tek sad vidim“ važi samo uz dokaz da je telefon nestao.",
    caseCode: "LATE01",
  },
  {
    id: "sr_excuse_tech_red",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["sr_no_internet", "sr_dead_phone"],
    reviewLine: "Tehnika daje izjavu.",
    sanction: "Crveni karton",
    offense: "Tehnički alibi",
    explanation: "Tehnika je preuzela punu odgovornost. Igrač nema daljih komentara.",
    penalty: "Tehnički izgovori suspendovani su do daljeg.",
    caseCode: "TECH01",
  },
  {
    id: "sr_excuse_generic_yellow",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Da li objašnjenje prolazi usporeni snimak?",
    sanction: "Žuti karton",
    offense: "Ne pije vodu",
    explanation: "Objašnjenje je stiglo. Snimak traži još jedan kadar.",
    penalty: "Jedno potpitanje ostaje obavezno.",
    caseCode: "ALIBI",
  },
  {
    id: "sr_plan_anything_red",
    locale: "sr",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["sr_dont_mind", "sr_reject_all"],
    fallback: true,
    reviewLine: "Da li je neka opcija uopšte imala šansu?",
    sanction: "Crveni karton",
    offense: "Svejedno, ali ne to",
    explanation: "Igrač želi pravo veta bez obaveze da smisli bolju opciju.",
    penalty: "Sledeće mesto bira, rezerviše i objašnjava grupi lično.",
    caseCode: "PLAN0",
  },
  {
    id: "sr_plan_choose_yellow",
    locale: "sr",
    categoryId: "planning_foul",
    severity: "yellow",
    triggerIds: ["sr_you_choose"],
    reviewLine: "Odluka je predata grupi. Navodno.",
    sanction: "Žuti karton",
    offense: "Vi birajte",
    explanation: "Izbor je prepušten grupi, ali je puno pravo žalbe zadržano.",
    penalty: "Sledeću odluku donosi igrač lično, bez prava žalbe.",
    caseCode: "CHOOSE",
  },
  {
    id: "sr_plan_veto_red",
    locale: "sr",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["sr_serial_rejection"],
    reviewLine: "VAR traži protivpredlog.",
    sanction: "Crveni karton",
    offense: "Veto bez predloga",
    explanation: "Veto je stigao. Predlog nije.",
    penalty: "Kauč trenutno vodi.",
    caseCode: "VETO1",
  },
  {
    id: "sr_offside_what_are_we_yellow",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["sr_what_are_we_early"],
    reviewLine: "Povlači se emotivna ofsajd linija.",
    sanction: "Žuti karton",
    offense: "Emotivni ofsajd",
    explanation: "Poruka pripada trećem mesecu veze. Razgovor je trenutno u trećem danu.",
    penalty: "Povratak iza linije i tri normalne poruke pre sledećeg napada.",
    caseCode: "OFFSIDE",
  },
  {
    id: "sr_offside_investigation_yellow",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["sr_early_jealousy"],
    reviewLine: "Da li je presing počeo pre dogovora?",
    sanction: "Žuti karton",
    offense: "Prerani presing",
    explanation: "Istraga je otvorena pre nego što je završen prvi ozbiljan razgovor.",
    penalty: "Dve obične poruke obavezne su pre sledeće provere statusa.",
    caseCode: "EARLY1",
  },
  {
    id: "sr_offside_where_going_red",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "red",
    triggerIds: ["sr_status_too_soon"],
    reviewLine: "Da li je sezona ubrzana bez razloga?",
    sanction: "Crveni karton",
    offense: "Ubrzavanje sezone",
    explanation: "Definicija odnosa zatražena je pre nego što je odnos dobio raspored.",
    penalty: "Tri normalne poruke pre sledeće konferencije o statusu.",
    caseCode: "STATUS",
  },
  {
    id: "sr_offside_generic_yellow",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Da li je linija pređena prerano?",
    sanction: "Žuti karton",
    offense: "Emotivni ofsajd",
    explanation: "Tempo poruke je otišao korak ispred tempa razgovora.",
    penalty: "Povratak iza linije. Igra se nastavlja normalno.",
    caseCode: "OFFGEN",
  },
  {
    id: "sr_missed_question_yellow",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["sr_avoided_question"],
    reviewLine: "Snimak se vraća na originalno pitanje.",
    sanction: "Žuti karton",
    offense: "Promašen zicer",
    explanation: "Pitanje je bilo na gol-liniji. Igrač je odgovorio na sporednu stvar.",
    penalty: "Obavezan povratak na pitanje u sledećoj poruci.",
    caseCode: "MISSED",
  },
  {
    id: "sr_missed_flirt_red",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "red",
    triggerIds: ["sr_missed_flirt"],
    reviewLine: "Da li je signal bio dovoljno jasan?",
    sanction: "Crveni karton",
    offense: "Promašen zicer",
    explanation: "Lopta je stigla pred prazan gol. Igrač je odgovorio sa „hahaha“ i promenio temu.",
    penalty: "Sledeći očigledan signal mora biti odigran iz prve.",
    caseCode: "FLIRT1",
  },
  {
    id: "sr_missed_side_yellow",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["sr_side_detail"],
    reviewLine: "Na šta je zapravo odgovoreno?",
    sanction: "Žuti karton",
    offense: "Pored teme",
    explanation: "Glavno pitanje je ostalo samo. Odgovor je otišao na najmanje važan detalj.",
    penalty: "Igra se nastavlja tek nakon povratka na originalno pitanje.",
    caseCode: "SIDE01",
  },
  {
    id: "sr_missed_generic_yellow",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Da li je ovo uopšte moglo da se promaši?",
    sanction: "Žuti karton",
    offense: "Promašen zicer",
    explanation: "Prilika je bila tu. Ostalo je igrač rešio sam.",
    penalty: "VAR nema šta da doda.",
    caseCode: "MISS0",
  },
] as const satisfies readonly VerdictVariant[]
