import type { VerdictVariant } from '../content-types'

export const srVerdicts = [
  {
    id: "sr_time_5min_red",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["sr_five_minutes", "sr_on_my_way"],
    reviewLine: "Da li je igrač uopšte krenuo?",
    sanction: "Crveni karton",
    offense: "Za krađu vremena",
    explanation: "Snimak potvrđuje da je u trenutku slanja poruke još birao šta će da obuče.",
    penalty: "Oduzima mu se pravo da kaže „krećem“ do kraja sezone.",
    caseCode: "5MIN",
  },
  {
    id: "sr_time_now_yellow",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: ["sr_leaving_now"],
    reviewLine: "Da li reč „sad“ ima važeći rok?",
    sanction: "Žuti karton",
    offense: "Za preranu najavu polaska",
    explanation: "Kretanje je objavljeno pre nego što su pronađeni ključevi, jakna i volja.",
    penalty: "Sledeće „krećem“ priznaje se tek nakon izlaska iz zgrade.",
    caseCode: "SAD01",
  },
  {
    id: "sr_time_warmup_red",
    locale: "sr",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["sr_almost_there", "sr_repeated_delay"],
    reviewLine: "Koliko zagrevanje može da traje?",
    sanction: "Crveni karton",
    offense: "Za beskonačno zagrevanje",
    explanation: "Igrač je tri puta završio spremanje i nijednom napustio stan.",
    penalty: "Vreme dolaska računa se tek od prvog koraka van kuće.",
    caseCode: "WARMUP",
  },
  {
    id: "sr_dry_vazi_yellow",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["sr_vazi", "sr_short_reply"],
    reviewLine: "Da li je ovo odgovor ili upozorenje?",
    sanction: "Žuti karton",
    offense: "Za odgovor bez pulsa",
    explanation: "Jedna reč. Nula topline. Maksimalna tenzija.",
    penalty: "Sledeća poruka mora da sadrži glagol i makar jedan znak života.",
    caseCode: "DRY01",
  },
  {
    id: "sr_dry_k_yellow",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["sr_k_reply"],
    reviewLine: "Da li jedno slovo ispunjava minimum?",
    sanction: "Žuti karton",
    offense: "Za skraćivanje saradnje",
    explanation: "Odgovor je stao na prvom slovu i odbio dalje učešće.",
    penalty: "Sledeća poruka mora da sadrži najmanje jednu celu reč.",
    caseCode: "KONLY",
  },
  {
    id: "sr_dry_reaction_red",
    locale: "sr",
    categoryId: "dry_texting",
    severity: "red",
    triggerIds: ["sr_reaction_only"],
    reviewLine: "Može li palac da odgovori na četiri pasusa?",
    sanction: "Crveni karton",
    offense: "Za odbranu reakcijom",
    explanation: "Na detaljnu poruku stigao je jedan palac i nijedan trag mišljenja.",
    penalty: "Reakcije su suspendovane dok se ne pojavi puna rečenica.",
    caseCode: "THUMB1",
  },
  {
    id: "sr_excuse_seen_red",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["sr_didnt_see", "sr_social_activity"],
    reviewLine: "Šta je igrač uspeo da vidi umesto poruke?",
    sanction: "Crveni karton",
    offense: "Za simuliranje",
    explanation: "Poruku možda nije video. Tri storija i jedan reel jesu.",
    penalty: "Tehnički izgovori suspendovani su naredna tri kola.",
    caseCode: "SEEN",
  },
  {
    id: "sr_excuse_just_saw_yellow",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "yellow",
    triggerIds: ["sr_just_saw"],
    reviewLine: "Kada je poruka zvanično primećena?",
    sanction: "Žuti karton",
    offense: "Za zakašnjelo viđenje",
    explanation: "Poruka je otkrivena tačno po isteku korisnog vremena za odgovor.",
    penalty: "Sledeće „tek sad vidim“ važi samo uz dokaz da je telefon nestao.",
    caseCode: "LATE01",
  },
  {
    id: "sr_excuse_offline_red",
    locale: "sr",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["sr_no_internet", "sr_dead_phone"],
    reviewLine: "Da li je internet nestao samo za ovu poruku?",
    sanction: "Crveni karton",
    offense: "Za selektivni gubitak signala",
    explanation: "Mreža nije radila za odgovor, ali je uredno prenela sve ostale aktivnosti.",
    penalty: "Izgovori o signalu nisu dostupni do daljeg.",
    caseCode: "NOINT",
  },
  {
    id: "sr_plan_anything_red",
    locale: "sr",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["sr_dont_mind", "sr_reject_all"],
    reviewLine: "Da li je neka opcija uopšte imala šansu?",
    sanction: "Crveni karton",
    offense: "Za svejedno, ali ne to",
    explanation: "Igrač želi pravo veta bez obaveze da smisli bolju opciju.",
    penalty: "Sledeće mesto bira, rezerviše i objašnjava grupi lično.",
    caseCode: "PLAN0",
  },
  {
    id: "sr_plan_choose_yellow",
    locale: "sr",
    categoryId: "planning_foul",
    severity: "yellow",
    triggerIds: ["sr_you_choose"],
    reviewLine: "Ko zapravo donosi odluku?",
    sanction: "Žuti karton",
    offense: "Za predaju odgovornosti",
    explanation: "Izbor je prepušten grupi, ali je puno pravo žalbe zadržano.",
    penalty: "Sledeći predlog mora da sadrži mesto, vreme i malo odlučnosti.",
    caseCode: "CHOOSE",
  },
  {
    id: "sr_plan_veto_red",
    locale: "sr",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["sr_serial_rejection"],
    reviewLine: "Koliko opcija mora da padne pre odluke?",
    sanction: "Crveni karton",
    offense: "Za serijski veto",
    explanation: "Pet predloga je odbijeno bez ijednog pokušaja zamene.",
    penalty: "Sledeći plan prelazi u potpunu nadležnost igrača.",
    caseCode: "VETO5",
  },
  {
    id: "sr_offside_early_yellow",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["sr_what_are_we_early"],
    reviewLine: "Povlačenje emotivne ofsajd linije.",
    sanction: "Žuti karton",
    offense: "Za emotivni ofsajd",
    explanation: "Poruka pripada trećem mesecu veze. Razgovor je trenutno u trećem danu.",
    penalty: "Povratak iza linije i tri normalne poruke pre sledećeg napada.",
    caseCode: "OFFSIDE",
  },
  {
    id: "sr_offside_press_yellow",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["sr_early_jealousy"],
    reviewLine: "Da li je presing počeo pre dogovora?",
    sanction: "Žuti karton",
    offense: "Za prerano presingovanje",
    explanation: "Istraga je otvorena pre nego što je završen prvi ozbiljan razgovor.",
    penalty: "Dve obične poruke obavezne su pre sledeće provere statusa.",
    caseCode: "PRESS1",
  },
  {
    id: "sr_offside_status_red",
    locale: "sr",
    categoryId: "emotional_offside",
    severity: "red",
    triggerIds: ["sr_status_too_soon"],
    reviewLine: "Da li je sezona ubrzana bez razloga?",
    sanction: "Crveni karton",
    offense: "Za ubrzavanje sezone",
    explanation: "Definicija odnosa zatražena je pre nego što je odnos dobio raspored.",
    penalty: "Obavezne su tri normalne poruke pre sledeće konferencije o statusu.",
    caseCode: "STATUS",
  },
  {
    id: "sr_missed_question_yellow",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["sr_avoided_question"],
    reviewLine: "Pregled promašenog zicera.",
    sanction: "Žuti karton",
    offense: "Za izbegavanje pitanja",
    explanation: "Pitanje je bilo na gol-liniji. Igrač je odgovorio na sporednu stvar.",
    penalty: "Obavezan povratak na pitanje u sledećoj poruci.",
    caseCode: "MISSED",
  },
  {
    id: "sr_missed_flirt_red",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "red",
    triggerIds: ["sr_missed_flirt"],
    reviewLine: "Da li je signal bio dovoljno jasan?",
    sanction: "Crveni karton",
    offense: "Za promašen flert",
    explanation: "Lopta je stigla pred prazan gol. Igrač je odgovorio sa „hahaha“ i promenio temu.",
    penalty: "Sledeći očigledan signal mora biti odigran iz prve.",
    caseCode: "FLIRT1",
  },
  {
    id: "sr_missed_side_yellow",
    locale: "sr",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["sr_side_detail"],
    reviewLine: "Na šta je zapravo odgovoreno?",
    sanction: "Žuti karton",
    offense: "Za igru po sporednoj temi",
    explanation: "Glavno pitanje je ostalo samo, dok je odgovor otišao na najmanje važan detalj.",
    penalty: "Igra se nastavlja tek nakon povratka na originalno pitanje.",
    caseCode: "SIDE01",
  },
] as const satisfies readonly VerdictVariant[]
