import type {
  IncidentCategoryId,
  Locale,
  SuggestionConfidence,
} from '../../shared/types/domain'

export type CategoryRule = {
  triggerId: string
  locale: Locale
  categoryId: IncidentCategoryId
  confidence: Exclude<SuggestionConfidence, 'none'>
  match: 'exact' | 'phrase'
  values: readonly string[]
  priority: number
}

export const categoryRules = [
  {
    triggerId: 'sr_leaving_now',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['krećem sad', 'krecem sad'],
    priority: 120,
  },
  {
    triggerId: 'sr_five_minutes',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['evo me za pet minuta', 'za 5 minuta', 'pet minuta'],
    priority: 110,
  },
  {
    triggerId: 'sr_almost_there',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['samo što nisam', 'samo sto nisam'],
    priority: 105,
  },
  {
    triggerId: 'sr_on_my_way',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['krećem', 'krecem', 'stižem', 'stizem', 'uskoro'],
    priority: 100,
  },
  {
    triggerId: 'sr_k_reply',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['k'],
    priority: 130,
  },
  {
    triggerId: 'sr_vazi',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['važi', 'vazi'],
    priority: 125,
  },
  {
    triggerId: 'sr_reaction_only',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['👍'],
    priority: 125,
  },
  {
    triggerId: 'sr_short_reply',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['ok', 'okej', 'mhm', 'dobro'],
    priority: 115,
  },
  {
    triggerId: 'sr_just_saw',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ['tek sad vidim'],
    priority: 120,
  },
  {
    triggerId: 'sr_didnt_see',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ['nisam video', 'nisam videla'],
    priority: 110,
  },
  {
    triggerId: 'sr_no_internet',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: [
      'nisam imao internet',
      'nisam imala internet',
      'nije bilo interneta',
    ],
    priority: 110,
  },
  {
    triggerId: 'sr_dead_phone',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ['telefon mi je bio', 'prazna baterija'],
    priority: 105,
  },
  {
    triggerId: 'sr_you_choose',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'phrase',
    values: [
      'birajte vi',
      'vi birajte',
      'može bilo gde',
      'moze bilo gde',
      'vi odlučite',
      'vi odlucite',
    ],
    priority: 115,
  },
  {
    triggerId: 'sr_dont_mind',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'phrase',
    values: ['svejedno', 'meni je svejedno', 'nije bitno', 'kako god'],
    priority: 105,
  },
  {
    triggerId: 'sr_early_jealousy',
    locale: 'sr',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: [
      'ko je ona',
      'ko je on',
      'zašto si lajkovao',
      'zasto si lajkovao',
      'zašto si lajkovala',
      'zasto si lajkovala',
    ],
    priority: 45,
  },
  {
    triggerId: 'sr_what_are_we_early',
    locale: 'sr',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: ['šta smo mi', 'sta smo mi', 'gde ovo vodi'],
    priority: 40,
  },

  {
    triggerId: 'en_leaving_now',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['leaving now', 'coming now'],
    priority: 120,
  },
  {
    triggerId: 'en_five_minutes',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['five minutes', '5 minutes'],
    priority: 110,
  },
  {
    triggerId: 'en_almost_there',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['almost there', 'be there soon'],
    priority: 105,
  },
  {
    triggerId: 'en_on_my_way',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'phrase',
    values: ['on my way'],
    priority: 100,
  },
  {
    triggerId: 'en_k_reply',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['k'],
    priority: 130,
  },
  {
    triggerId: 'en_reaction_only',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['👍'],
    priority: 125,
  },
  {
    triggerId: 'en_fine',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['fine'],
    priority: 125,
  },
  {
    triggerId: 'en_short_reply',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['ok', 'okay', 'sure', 'mhm'],
    priority: 115,
  },
  {
    triggerId: 'en_just_saw',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ['just saw this'],
    priority: 120,
  },
  {
    triggerId: 'en_didnt_see',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ["didn't see", 'didnt see'],
    priority: 110,
  },
  {
    triggerId: 'en_no_internet',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ['no internet', 'no signal'],
    priority: 110,
  },
  {
    triggerId: 'en_dead_phone',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'phrase',
    values: ['phone was dead', 'battery died'],
    priority: 105,
  },
  {
    triggerId: 'en_you_choose',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'phrase',
    values: ['you choose'],
    priority: 115,
  },
  {
    triggerId: 'en_dont_mind',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'phrase',
    values: [
      "i don't mind",
      'i dont mind',
      'anything is fine',
      'wherever',
      "doesn't matter",
      'doesnt matter',
    ],
    priority: 105,
  },
  {
    triggerId: 'en_early_jealousy',
    locale: 'en',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: ['who is she', 'who is he', 'why did you like'],
    priority: 45,
  },
  {
    triggerId: 'en_what_are_we_early',
    locale: 'en',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: ['what are we', 'where is this going'],
    priority: 40,
  },
] as const satisfies readonly CategoryRule[]
