import type {
  IncidentCategoryId,
  Locale,
  SuggestionConfidence,
} from '../../shared/types/domain'

export type CategoryRule = {
  triggerId: string
  locale: Locale
  categoryId: IncidentCategoryId
  confidence: Exclude<SuggestionConfidence, 'none'>
  match: 'exact' | 'phrase'
  values: readonly string[]
  priority: number
  suggest?: boolean
  verdictSpecific?: boolean
}

export const categoryRules = [
  {
    triggerId: 'sr_leaving_now',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: ['krećem sad', 'krecem sad', 'sad krećem', 'sad krecem'],
    priority: 120,
  },
  {
    triggerId: 'sr_five_minutes',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: [
      'evo me za pet minuta',
      'evo me za 5 minuta',
      'tu sam za pet minuta',
      'tu sam za 5 minuta',
      'stižem za pet minuta',
      'stizem za pet minuta',
      'stižem za 5 minuta',
      'stizem za 5 minuta',
    ],
    priority: 110,
  },
  {
    triggerId: 'sr_almost_there',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: ['samo što nisam', 'samo sto nisam'],
    priority: 105,
  },
  {
    triggerId: 'sr_repeated_delay',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'low',
    match: 'exact',
    values: [
      'još malo',
      'jos malo',
      'evo samo još malo',
      'evo samo jos malo',
      'sad ću',
      'sad cu',
      'evo sad ću',
      'evo sad cu',
    ],
    priority: 62,
  },
  {
    triggerId: 'sr_on_my_way',
    locale: 'sr',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: [
      'krećem',
      'krecem',
      'stižem',
      'stizem',
      'uskoro',
      'evo krećem',
      'evo krecem',
      'evo stižem',
      'evo stizem',
      'tu sam uskoro',
    ],
    priority: 100,
  },
  {
    triggerId: 'sr_k_reply',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['k'],
    priority: 130,
  },
  {
    triggerId: 'sr_vazi',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['važi', 'vazi'],
    priority: 125,
  },
  {
    triggerId: 'sr_reaction_only',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['👍'],
    priority: 125,
  },
  {
    triggerId: 'sr_short_reply',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['ok', 'okej', 'mhm'],
    priority: 115,
  },
  {
    triggerId: 'sr_dry_contextual',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'low',
    match: 'exact',
    values: ['dobro'],
    priority: 60,
  },
  {
    triggerId: 'sr_dry_acknowledgment',
    locale: 'sr',
    categoryId: 'dry_texting',
    confidence: 'low',
    match: 'exact',
    values: ['aha'],
    priority: 55,
    verdictSpecific: false,
  },
  {
    triggerId: 'sr_just_saw',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      'tek sad vidim',
      'tek sad vidim izvini',
      'tek sad vidim poruku',
      'sad sam video poruku',
      'sad sam videla poruku',
    ],
    priority: 120,
  },
  {
    triggerId: 'sr_didnt_see',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      'nisam video poruku',
      'nisam videla poruku',
      'nisam video tvoju poruku',
      'nisam videla tvoju poruku',
      'promakla mi je poruka',
    ],
    priority: 110,
  },
  {
    triggerId: 'sr_no_internet',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      'nisam imao internet',
      'nisam imala internet',
      'nije bilo interneta',
      'nisam imao signal',
      'nisam imala signal',
      'nije bilo signala',
    ],
    priority: 110,
  },
  {
    triggerId: 'sr_dead_phone',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      'prazna baterija',
      'telefon mi se ugasio',
      'ugasio mi se telefon',
      'baterija mi se ispraznila',
      'bio mi je prazan telefon',
    ],
    priority: 105,
  },
  {
    triggerId: 'sr_partial_seen_excuse',
    locale: 'sr',
    categoryId: 'suspicious_excuse',
    confidence: 'low',
    match: 'exact',
    values: [
      'sad vidim',
      'tek vidim',
      'nisam video',
      'nisam videla',
    ],
    priority: 70,
    verdictSpecific: false,
  },
  {
    triggerId: 'sr_you_choose',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'exact',
    values: [
      'birajte vi',
      'vi birajte',
      'može bilo gde',
      'moze bilo gde',
      'vi odlučite',
      'vi odlucite',
      'ti biraj',
      'biraj ti',
      'odluči ti',
      'odluci ti',
      'meni sve odgovara',
      'meni odgovara bilo gde',
    ],
    priority: 115,
  },
  {
    triggerId: 'sr_dont_mind',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'exact',
    values: [
      'svejedno',
      'meni je svejedno',
      'meni svejedno',
      'nije bitno',
      'kako god',
      'može šta god',
      'moze sta god',
    ],
    priority: 105,
  },
  {
    triggerId: 'sr_reject_all',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'exact',
    values: [
      'neću ni jedno',
      'necu ni jedno',
      'ništa od toga',
      'nista od toga',
      'ne sviđa mi se ništa',
      'ne svidja mi se nista',
    ],
    priority: 110,
  },
  {
    triggerId: 'sr_serial_rejection',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'low',
    match: 'phrase',
    values: [
      'ne tad, ne tamo',
      'ne može tad ni tamo',
      'ne moze tad ni tamo',
      'ne tamo, ne tad',
      'ni tad ni tamo',
    ],
    priority: 65,
  },
  {
    triggerId: 'sr_open_choice',
    locale: 'sr',
    categoryId: 'planning_foul',
    confidence: 'low',
    match: 'exact',
    values: [
      'kako hoćeš',
      'kako hoces',
      'šta god',
      'sta god',
    ],
    priority: 55,
    verdictSpecific: false,
  },
  {
    triggerId: 'sr_early_jealousy',
    locale: 'sr',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: [
      'ko je ona',
      'ko je on',
      'zašto si lajkovao',
      'zasto si lajkovao',
      'zašto si lajkovala',
      'zasto si lajkovala',
      'ko ti je ona',
      'ko ti je on',
      'što si lajkovao',
      'sto si lajkovao',
      'što si lajkovala',
      'sto si lajkovala',
    ],
    priority: 45,
  },
  {
    triggerId: 'sr_what_are_we_early',
    locale: 'sr',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: [
      'šta smo mi',
      'sta smo mi',
      'a šta smo mi',
      'a sta smo mi',
      'šta smo onda mi',
      'sta smo onda mi',
    ],
    priority: 40,
  },
  {
    triggerId: 'sr_status_too_soon',
    locale: 'sr',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: ['gde ovo vodi', 'kuda ovo vodi'],
    priority: 40,
  },
  {
    triggerId: 'sr_relationship_probe',
    locale: 'sr',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'exact',
    values: [
      'jesmo mi zajedno',
      'šta je ovo između nas',
      'sta je ovo izmedju nas',
      'gde ovo ide',
    ],
    priority: 38,
    verdictSpecific: false,
  },
  {
    triggerId: 'sr_missed_flirt',
    locale: 'sr',
    categoryId: 'missed_chance',
    confidence: 'low',
    match: 'exact',
    values: ['haha', 'hahaha', 'ahahah', 'ahahaha'],
    priority: 35,
    suggest: false,
  },
  {
    triggerId: 'en_leaving_now',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: ['leaving now', 'coming now', 'heading out now'],
    priority: 120,
  },
  {
    triggerId: 'en_five_minutes',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: [
      'five minutes away',
      '5 minutes away',
      "i'm five minutes away",
      'im five minutes away',
      'i am five minutes away',
      "i'm 5 minutes away",
      'im 5 minutes away',
      'i am 5 minutes away',
      'be there in five minutes',
      'be there in 5 minutes',
      "i'll be there in five minutes",
      'ill be there in five minutes',
      "i'll be there in 5 minutes",
      'ill be there in 5 minutes',
      'in five minutes',
      'in 5 minutes',
    ],
    priority: 110,
  },
  {
    triggerId: 'en_almost_there',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: ['almost there', 'be there soon'],
    priority: 105,
  },
  {
    triggerId: 'en_repeated_delay',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'low',
    match: 'exact',
    values: ['almost ready', 'nearly ready', 'just a little longer'],
    priority: 62,
  },
  {
    triggerId: 'en_on_my_way',
    locale: 'en',
    categoryId: 'time_wasting',
    confidence: 'high',
    match: 'exact',
    values: ['on my way', 'on the way', 'heading over', 'heading there'],
    priority: 100,
  },
  {
    triggerId: 'en_k_reply',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['k'],
    priority: 130,
  },
  {
    triggerId: 'en_reaction_only',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['👍'],
    priority: 125,
  },
  {
    triggerId: 'en_sure',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['sure'],
    priority: 125,
  },
  {
    triggerId: 'en_fine',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['fine'],
    priority: 125,
  },
  {
    triggerId: 'en_short_reply',
    locale: 'en',
    categoryId: 'dry_texting',
    confidence: 'high',
    match: 'exact',
    values: ['ok', 'okay', 'mhm'],
    priority: 115,
  },
  {
    triggerId: 'en_just_saw',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      'just saw this',
      'sorry just saw this',
      'just saw your message',
      'sorry just saw your message',
      'only just saw this',
    ],
    priority: 120,
  },
  {
    triggerId: 'en_didnt_see',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      "didn't see your message",
      'didnt see your message',
      'missed your message',
      'sorry missed your message',
    ],
    priority: 110,
  },
  {
    triggerId: 'en_no_internet',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: ['no internet', 'no signal', 'had no signal', 'lost signal', 'had no service'],
    priority: 110,
  },
  {
    triggerId: 'en_dead_phone',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'high',
    match: 'exact',
    values: [
      'phone was dead',
      'my phone died',
      'battery died',
      'phone died',
      'battery was dead',
      'my phone was off',
    ],
    priority: 105,
  },
  {
    triggerId: 'en_partial_seen_excuse',
    locale: 'en',
    categoryId: 'suspicious_excuse',
    confidence: 'low',
    match: 'exact',
    values: [
      'just seeing this',
      'seeing this now',
      'just noticed this',
    ],
    priority: 70,
    verdictSpecific: false,
  },
  {
    triggerId: 'en_you_choose',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'exact',
    values: ['you choose', 'you pick', 'you decide', 'your call', 'up to you'],
    priority: 115,
  },
  {
    triggerId: 'en_dont_mind',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'exact',
    values: [
      "i don't mind",
      'i dont mind',
      'anything is fine',
      'anything works',
      'wherever is fine',
    ],
    priority: 105,
  },
  {
    triggerId: 'en_reject_all',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'high',
    match: 'exact',
    values: [
      'none of those',
      'not any of those',
      "i don't like any of them",
      'i dont like any of them',
      'nothing there works',
    ],
    priority: 110,
  },
  {
    triggerId: 'en_serial_rejection',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'low',
    match: 'phrase',
    values: [
      'not then, not there',
      'not there, not then',
      'neither then nor there',
    ],
    priority: 65,
  },
  {
    triggerId: 'en_open_choice',
    locale: 'en',
    categoryId: 'planning_foul',
    confidence: 'low',
    match: 'exact',
    values: ['whatever you want'],
    priority: 55,
    verdictSpecific: false,
  },
  {
    triggerId: 'en_early_jealousy',
    locale: 'en',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: [
      'who is she',
      'who is he',
      "who's she",
      'whos she',
      "who's he",
      'whos he',
      'who is that',
      'why did you like',
      'why did you like her',
      'why did you like him',
    ],
    priority: 45,
  },
  {
    triggerId: 'en_what_are_we_early',
    locale: 'en',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: ['what are we', 'so what are we', 'what are we then'],
    priority: 40,
  },
  {
    triggerId: 'en_status_too_soon',
    locale: 'en',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'phrase',
    values: [
      'where is this going',
      'where is this headed',
      'where is this going between us',
    ],
    priority: 40,
  },
  {
    triggerId: 'en_relationship_probe',
    locale: 'en',
    categoryId: 'emotional_offside',
    confidence: 'low',
    match: 'exact',
    values: ['are we together', 'what is this between us'],
    priority: 38,
    verdictSpecific: false,
  },
  {
    triggerId: 'en_missed_flirt',
    locale: 'en',
    categoryId: 'missed_chance',
    confidence: 'low',
    match: 'exact',
    values: ['haha', 'hahaha', 'ahahah'],
    priority: 35,
    suggest: false,
  },
] as const satisfies readonly CategoryRule[]
