import type { VerdictVariant } from '../content-types'

export const enVerdicts = [
  {
    id: "en_time_5min_red",
    locale: "en",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["en_five_minutes"],
    reviewLine: "Has the player actually left yet?",
    sanction: "Red card",
    offense: "Five minutes away",
    explanation: "Footage confirms the message was sent while the player was still deciding what to wear.",
    penalty: "The phrase “on my way” is suspended for the rest of the season.",
    caseCode: "5MIN",
  },
  {
    id: "en_time_status_yellow",
    locale: "en",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: ["en_on_my_way", "en_repeated_delay"],
    reviewLine: "Is this an arrival time?",
    sanction: "Yellow card",
    offense: "Arrival pending",
    explanation: "The status update arrived. The arrival time didn’t.",
    penalty: "The next update must include a time.",
    caseCode: "ETA01",
  },
  {
    id: "en_time_now_yellow",
    locale: "en",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: ["en_leaving_now"],
    reviewLine: "When does “now” officially begin?",
    sanction: "Yellow card",
    offense: "Leaving now",
    explanation: "The message was sent before the keys, jacket, and motivation were located.",
    penalty: "Future updates count only after the front door closes.",
    caseCode: "OMW01",
  },
  {
    id: "en_time_almost_red",
    locale: "en",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["en_almost_there"],
    reviewLine: "How long can “almost there” remain active?",
    sanction: "Red card",
    offense: "Endless warm-up",
    explanation: "The player completed three getting-ready phases without leaving the house.",
    penalty: "Arrival estimates may resume after visible movement.",
    caseCode: "ALMOST",
  },
  {
    id: "en_time_generic_yellow",
    locale: "en",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Does the clock support this version?",
    sanction: "Yellow card",
    offense: "Timing under review",
    explanation: "Time entered the case. The clock is refusing to confirm the details.",
    penalty: "The next estimate gets no added time.",
    caseCode: "TIME0",
  },
  {
    id: "en_dry_sure_yellow",
    locale: "en",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["en_sure"],
    reviewLine: "Is this a reply or a warning?",
    sanction: "Yellow card",
    offense: "Dry",
    explanation: "“Sure.” lands and now you’re rereading the chat to see where you messed up.",
    penalty: "No “are you mad?” for ten minutes.",
    caseCode: "DRY01",
  },
  {
    id: "en_dry_short_yellow",
    locale: "en",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["en_short_reply", "en_fine"],
    reviewLine: "Is this really all the footage?",
    sanction: "Yellow card",
    offense: "Dry",
    explanation: "The reply took a second. The analysis is going into extra time.",
    penalty: "No rereading the chat until the next message.",
    caseCode: "DRY02",
  },
  {
    id: "en_dry_k_yellow",
    locale: "en",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["en_k_reply"],
    reviewLine: "Does one letter meet the minimum?",
    sanction: "Yellow card",
    offense: "K.",
    explanation: "“K.” just made “okay” look generous.",
    penalty: "The next reply must include at least one complete word.",
    caseCode: "KONLY",
  },
  {
    id: "en_dry_reaction_red",
    locale: "en",
    categoryId: "dry_texting",
    severity: "red",
    triggerIds: ["en_reaction_only"],
    reviewLine: "Does the reaction end the conversation?",
    sanction: "Red card",
    offense: "Thumbs-up. That’s it.",
    explanation: "The 👍 is clear. Everything around it is still under review.",
    penalty: "Reactions are suspended until a full sentence appears.",
    caseCode: "THUMB1",
  },
  {
    id: "en_dry_generic_yellow",
    locale: "en",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Does the conversation still have a pulse?",
    sanction: "Yellow card",
    offense: "Dry",
    explanation: "The message arrived. The atmosphere stayed out of frame.",
    penalty: "No forensic analysis of punctuation on the next play.",
    caseCode: "DRY00",
  },
  {
    id: "en_excuse_seen_red",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["en_didnt_see"],
    reviewLine: "Excuse under review.",
    sanction: "Red card",
    offense: "Simulation",
    explanation: "The message was apparently missed. The reply to it arrived just fine.",
    penalty: "Technical excuses are suspended for the next three rounds.",
    caseCode: "SEEN",
  },
  {
    id: "en_excuse_just_saw_yellow",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "yellow",
    triggerIds: ["en_just_saw"],
    reviewLine: "The timing of “just” is under review.",
    sanction: "Yellow card",
    offense: "Just now?",
    explanation: "“Just saw this.” Right now. Incredible timing.",
    penalty: "The next “just saw this” requires evidence that the phone went missing.",
    caseCode: "LATE01",
  },
  {
    id: "en_excuse_tech_red",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["en_no_internet", "en_dead_phone"],
    reviewLine: "Technology takes the stand.",
    sanction: "Red card",
    offense: "Yeah, right",
    explanation: "Technology has accepted full responsibility. The player has no further comment.",
    penalty: "Technical excuses are suspended until further notice.",
    caseCode: "TECH01",
  },
  {
    id: "en_excuse_generic_yellow",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Does the explanation survive the replay?",
    sanction: "Yellow card",
    offense: "Yeah, right",
    explanation: "The explanation arrived. The replay still wants one more angle.",
    penalty: "One follow-up question remains mandatory.",
    caseCode: "ALIBI",
  },
  {
    id: "en_plan_anything_red",
    locale: "en",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["en_dont_mind", "en_reject_all"],
    reviewLine: "Was any option ever going to survive?",
    sanction: "Red card",
    offense: "Anything but that",
    explanation: "Anything is fine right up until someone suggests something.",
    penalty: "The next venue must be chosen, booked, and explained personally.",
    caseCode: "PLAN0",
  },
  {
    id: "en_plan_choose_yellow",
    locale: "en",
    categoryId: "planning_foul",
    severity: "yellow",
    triggerIds: ["en_you_choose"],
    reviewLine: "Decision handed over. Allegedly.",
    sanction: "Yellow card",
    offense: "You choose",
    explanation: "The player handed the choice to the group and kept full appeal rights.",
    penalty: "The next decision belongs to the player, with no right of appeal.",
    caseCode: "CHOOSE",
  },
  {
    id: "en_plan_veto_red",
    locale: "en",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["en_serial_rejection"],
    reviewLine: "VAR is still looking for a counterproposal.",
    sanction: "Red card",
    offense: "All veto, no plan",
    explanation: "The veto showed up. The suggestion didn’t.",
    penalty: "The couch is currently winning.",
    caseCode: "VETO1",
  },
  {
    id: "en_plan_generic_yellow",
    locale: "en",
    categoryId: "planning_foul",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Is the plan actually moving?",
    sanction: "Yellow card",
    offense: "Plan under review",
    explanation: "The plan entered VAR. There is not enough footage for a harsher ruling.",
    penalty: "The next move must bring the group closer to a decision.",
    caseCode: "PLAN00",
  },
  {
    id: "en_offside_what_are_we_yellow",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["en_what_are_we_early"],
    reviewLine: "Drawing the emotional offside line.",
    sanction: "Yellow card",
    offense: "Emotional offside",
    explanation: "The message belongs in month three. The conversation is currently on day three.",
    penalty: "Return behind the line and complete three normal messages before the next attack.",
    caseCode: "OFFSIDE",
  },
  {
    id: "en_offside_investigation_yellow",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["en_early_jealousy"],
    reviewLine: "Did the pressure arrive before the agreement?",
    sanction: "Yellow card",
    offense: "Early press",
    explanation: "An investigation opened before the first serious conversation had even finished.",
    penalty: "Two ordinary messages are required before the next status check.",
    caseCode: "EARLY1",
  },
  {
    id: "en_offside_where_going_red",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "red",
    triggerIds: ["en_status_too_soon"],
    reviewLine: "Did the season get fast-forwarded?",
    sanction: "Red card",
    offense: "Rushing the season",
    explanation: "A relationship definition was requested before the relationship had a schedule.",
    penalty: "Three normal messages are required before the next status press conference.",
    caseCode: "STATUS",
  },
  {
    id: "en_offside_generic_yellow",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Did the message cross the line early?",
    sanction: "Yellow card",
    offense: "Emotional offside",
    explanation: "The message moved one step ahead of the conversation.",
    penalty: "Back behind the line. Play continues normally.",
    caseCode: "OFFGEN",
  },
  {
    id: "en_missed_question_yellow",
    locale: "en",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["en_avoided_question"],
    reviewLine: "Footage returns to the original question.",
    sanction: "Yellow card",
    offense: "Missed sitter",
    explanation: "The question was on the goal line. The reply went after a side detail.",
    penalty: "The next message must return to the original question.",
    caseCode: "MISSED",
  },
  {
    id: "en_missed_flirt_red",
    locale: "en",
    categoryId: "missed_chance",
    severity: "red",
    triggerIds: ["en_missed_flirt"],
    reviewLine: "Was the signal clear enough?",
    sanction: "Red card",
    offense: "Missed sitter",
    explanation: "The ball arrived in front of an empty net. The player replied “haha” and changed the subject.",
    penalty: "The next obvious signal must be taken first time.",
    caseCode: "FLIRT1",
  },
  {
    id: "en_missed_side_yellow",
    locale: "en",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["en_side_detail"],
    reviewLine: "What did the player actually answer?",
    sanction: "Yellow card",
    offense: "Missed the point",
    explanation: "The main question was left unmarked while the reply chased the least important detail.",
    penalty: "Play must restart from the original question.",
    caseCode: "SIDE01",
  },
  {
    id: "en_missed_generic_yellow",
    locale: "en",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: [],
    fallback: true,
    reviewLine: "Was this really possible to miss?",
    sanction: "Yellow card",
    offense: "Missed sitter",
    explanation: "The chance was there. Everything after that was self-inflicted.",
    penalty: "VAR has nothing to add.",
    caseCode: "MISS0",
  },
] as const satisfies readonly VerdictVariant[]
