import type { VerdictVariant } from '../content-types'

export const enVerdicts = [
  {
    id: "en_time_5min_red",
    locale: "en",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["en_five_minutes", "en_on_my_way"],
    reviewLine: "Has the player actually left yet?",
    sanction: "Red card",
    offense: "For time-wasting",
    explanation: "Footage confirms the message was sent while the player was still deciding what to wear.",
    penalty: "The phrase “on my way” is suspended for the rest of the season.",
    caseCode: "5MIN",
  },
  {
    id: "en_time_now_yellow",
    locale: "en",
    categoryId: "time_wasting",
    severity: "yellow",
    triggerIds: ["en_leaving_now"],
    reviewLine: "When does “on my way” officially begin?",
    sanction: "Yellow card",
    offense: "For premature departure claims",
    explanation: "The journey was announced before the keys, jacket, and motivation were located.",
    penalty: "Future updates count only after the front door closes.",
    caseCode: "OMW01",
  },
  {
    id: "en_time_warmup_red",
    locale: "en",
    categoryId: "time_wasting",
    severity: "red",
    triggerIds: ["en_almost_there", "en_repeated_delay"],
    reviewLine: "How long can “almost there” remain active?",
    sanction: "Red card",
    offense: "For endless warm-up",
    explanation: "The player completed three getting-ready phases without leaving the house.",
    penalty: "Arrival estimates may resume after visible movement.",
    caseCode: "WARMUP",
  },
  {
    id: "en_dry_fine_yellow",
    locale: "en",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["en_fine", "en_short_reply"],
    reviewLine: "Is this a reply or a warning?",
    sanction: "Yellow card",
    offense: "For a dead reply",
    explanation: "One word. No warmth. Full tension.",
    penalty: "The next message must contain a verb and at least one sign of life.",
    caseCode: "DRY01",
  },
  {
    id: "en_dry_k_yellow",
    locale: "en",
    categoryId: "dry_texting",
    severity: "yellow",
    triggerIds: ["en_k_reply"],
    reviewLine: "Does one letter meet the minimum?",
    sanction: "Yellow card",
    offense: "For communication cut short",
    explanation: "The response stopped at the first letter and declined further participation.",
    penalty: "The next reply must include at least one complete word.",
    caseCode: "KONLY",
  },
  {
    id: "en_dry_reaction_red",
    locale: "en",
    categoryId: "dry_texting",
    severity: "red",
    triggerIds: ["en_reaction_only"],
    reviewLine: "Can one thumbs-up answer four paragraphs?",
    sanction: "Red card",
    offense: "For reaction-only defending",
    explanation: "A detailed message received one thumb and no detectable opinion.",
    penalty: "Reactions are suspended until a full sentence appears.",
    caseCode: "THUMB1",
  },
  {
    id: "en_excuse_seen_red",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["en_didnt_see", "en_social_activity"],
    reviewLine: "What did the player manage to see instead?",
    sanction: "Red card",
    offense: "For simulation",
    explanation: "The message may have been missed. Three stories and a reel were not.",
    penalty: "Technical excuses are suspended for the next three rounds.",
    caseCode: "SEEN",
  },
  {
    id: "en_excuse_just_saw_yellow",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "yellow",
    triggerIds: ["en_just_saw"],
    reviewLine: "When was the message officially discovered?",
    sanction: "Yellow card",
    offense: "For delayed visibility",
    explanation: "The message became visible immediately after the useful reply window closed.",
    penalty: "The next “just saw this” requires evidence that the phone went missing.",
    caseCode: "LATE01",
  },
  {
    id: "en_excuse_offline_red",
    locale: "en",
    categoryId: "suspicious_excuse",
    severity: "red",
    triggerIds: ["en_no_internet", "en_dead_phone"],
    reviewLine: "Did the internet fail for this message only?",
    sanction: "Red card",
    offense: "For selective signal loss",
    explanation: "The connection failed to deliver a reply but handled every other activity without issue.",
    penalty: "Connectivity-based defenses are unavailable until further notice.",
    caseCode: "NOINT",
  },
  {
    id: "en_plan_anything_red",
    locale: "en",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["en_dont_mind", "en_reject_all"],
    reviewLine: "Was any option ever going to survive?",
    sanction: "Red card",
    offense: "For anything but that",
    explanation: "The player rejected every suggestion while submitting none of their own.",
    penalty: "The next venue must be chosen, booked, and explained personally.",
    caseCode: "PLAN0",
  },
  {
    id: "en_plan_choose_yellow",
    locale: "en",
    categoryId: "planning_foul",
    severity: "yellow",
    triggerIds: ["en_you_choose"],
    reviewLine: "Who is actually making the decision?",
    sanction: "Yellow card",
    offense: "For outsourcing the plan",
    explanation: "The player handed the choice to the group and kept full appeal rights.",
    penalty: "The next suggestion must include a place, a time, and some commitment.",
    caseCode: "CHOOSE",
  },
  {
    id: "en_plan_veto_red",
    locale: "en",
    categoryId: "planning_foul",
    severity: "red",
    triggerIds: ["en_serial_rejection"],
    reviewLine: "How many options must fall before a decision?",
    sanction: "Red card",
    offense: "For serial rejection",
    explanation: "Five options were dismissed without a replacement entering the field.",
    penalty: "The player now owns the next plan from idea to reservation.",
    caseCode: "VETO5",
  },
  {
    id: "en_offside_early_yellow",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["en_what_are_we_early"],
    reviewLine: "Drawing the emotional offside line.",
    sanction: "Yellow card",
    offense: "For emotional offside",
    explanation: "The message belongs in month three. The conversation is currently on day three.",
    penalty: "Return behind the line and complete three normal messages before the next attack.",
    caseCode: "OFFSIDE",
  },
  {
    id: "en_offside_press_yellow",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "yellow",
    triggerIds: ["en_early_jealousy"],
    reviewLine: "Did the pressure arrive before the agreement?",
    sanction: "Yellow card",
    offense: "For early pressing",
    explanation: "An investigation opened before the first serious conversation had even finished.",
    penalty: "Two ordinary messages are required before the next status check.",
    caseCode: "PRESS1",
  },
  {
    id: "en_offside_status_red",
    locale: "en",
    categoryId: "emotional_offside",
    severity: "red",
    triggerIds: ["en_status_too_soon"],
    reviewLine: "Did the season get fast-forwarded?",
    sanction: "Red card",
    offense: "For rushing the season",
    explanation: "A relationship definition was requested before the relationship had a schedule.",
    penalty: "Three normal messages are required before the next status press conference.",
    caseCode: "STATUS",
  },
  {
    id: "en_missed_question_yellow",
    locale: "en",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["en_avoided_question"],
    reviewLine: "Reviewing a missed sitter.",
    sanction: "Yellow card",
    offense: "For avoiding the question",
    explanation: "The question was on the goal line. The reply went after a side detail.",
    penalty: "The next message must return to the original question.",
    caseCode: "MISSED",
  },
  {
    id: "en_missed_flirt_red",
    locale: "en",
    categoryId: "missed_chance",
    severity: "red",
    triggerIds: ["en_missed_flirt"],
    reviewLine: "Was the signal clear enough?",
    sanction: "Red card",
    offense: "For missing an open flirt",
    explanation: "The ball arrived in front of an empty net. The player replied “haha” and changed the subject.",
    penalty: "The next obvious signal must be taken first time.",
    caseCode: "FLIRT1",
  },
  {
    id: "en_missed_side_yellow",
    locale: "en",
    categoryId: "missed_chance",
    severity: "yellow",
    triggerIds: ["en_side_detail"],
    reviewLine: "What did the player actually answer?",
    sanction: "Yellow card",
    offense: "For playing the side topic",
    explanation: "The main question was left unmarked while the reply chased the least important detail.",
    penalty: "Play must restart from the original question.",
    caseCode: "SIDE01",
  },
] as const satisfies readonly VerdictVariant[]
